version: 0.2

env:
  variables:
    PROJECT_NAME: "MyWebsite"
    S3_BUCKET_NAME: "my-website-bucket"  # Replace with your S3 bucket name

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      echo "Installing dependencies"
      npm install
      echo "Installed dependencies"
      npm list  # List installed npm packages to debug potential issues
      echo "Installing AWS CLI"
      pip install awscli
      echo "AWS CLI installed"
      aws --version  # Ensure AWS CLI is installed

  pre_build:
    commands:
      echo "Running pre-build tasks"
      npm run lint
      npm run test

  build:
    commands:
      -echo "building project...(In this case,no build is needed--testing--)"
      

  post_build:
    commands:
      echo "Uploading files to S3 bucket"
      ls -al ./build/  # Confirm the build folder contents before upload
      aws s3 cp ./build/ s3://$S3_BUCKET_NAME/ --recursive

artifacts:
  files:
    - '**/*'  # Include all files for the build artifact
  base-directory: build  # Specify the directory where build artifacts are located

cache:
  paths:
    - 'node_modules/**/*'  # Cache dependencies to speed up future builds


